FROM quay.io/toolbx-images/centos-toolbox:stream9

COPY extra-packages /

RUN dnf -y install $(<extra-packages)
RUN git clone https://github.com/softwarefactory-project/DLRN.git && \
    pushd DLRN && \
	pip3 install .

RUN chown -R root:mock /DLRN
RUN chmod 666 /DLRN
RUN find /DLRN -type f -name "*.*" -exec chmod 664 {} \;
RUN find /DLRN -type d -exec chmod 775 {} \;

COPY functions.sh /functions.sh
RUN cat /functions.sh >> /etc/profile.d/functions.sh

RUN sed -i 's|datadir=.*|datadir=/DLRN/data|' /DLRN/projects.ini

RUN useradd -G mock -s /bin/bash -d /home/dlrn dlrn
USER dlrn
WORKDIR /DLRN

