FROM quay.io/fedora/fedora-sericea:40

LABEL maintainer=jcapitao

RUN rpm-ostree install \
  https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-40.noarch.rpm \
  https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-40.noarch.rpm

COPY extra-packages /
RUN rpm-ostree install -y $(</extra-packages)
RUN rm /extra-packages
