FROM quay.io/fedora/fedora-sericea:39

LABEL maintainer=jcapitao

RUN rpm-ostree install \
  https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
  https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

COPY extra-packages /
RUN rpm-ostree install -y $(</extra-packages)
RUN rm /extra-packages
